const fs = require('fs');

const d = {
  es: {
    "rec-title": "Recursos y Vínculos Oficiales",
    "rec-h1": "Recursos Oficiales",
    "rec-desc": "Directorio verificado de la administración suiza y portales clave para emigrantes.",
    "rec-ch-p": "El portal nacional suizo administrado por el gobierno federal en 5 idiomas. La principal fuente de verdad inicial.",
    "rec-ch-link": "Visitar ch.ch &rarr;",
    "rec-sem-p": "Secretaría de Estado de Migración. Directivas federales sobre la expedición de tipos de permiso y naturalización.",
    "rec-sem-link": "Visitar SEM &rarr;",
    "rec-comp-p": "Plataforma para comparar los precios de las primas del seguro médico cantón por cantón, así como seguros de coche y fianzas de alquiler.",
    "rec-comp-link": "Visitar Comparis &rarr;",
    "rec-canton-title": "Página web de tu cantón",
    "rec-canton-p": "La estructura descentralizada indica que tu cantón gestiona el cobro de impuestos, el paro y la expedición del permiso. Por ejemplo vd.ch (Vaud), ge.ch (Ginebra).",
    "com-nav": "Comunidad",
    "com-h1": "De un grupo de ayuda, a esta plataforma de conocimiento.",
    "com-desc": "Nuestra web extrae el conocimiento verídico y los problemas más recurrentes que surgen a diario de nuestra vibrante comunidad en Facebook.",
    "com-p1": "<strong>Españoles en Suiza que realmente se ayudan</strong> nació como un grupo privado de FB para filtrar el ruido y proporcionar respuestas fiables a recién llegados y residentes.",
    "com-p2": "Hoy somos miles de miembros aportando valor, alertando sobre estafas de alquiler y ayudando a entender la burocracia suiza.",
    "com-li1": "Resolución ágil de dudas sobre el permiso y la LAMal.",
    "com-li2": "Ofertas de alojamiento de traspaso directo (sin agencia).",
    "com-li3": "Networking y recomendación de profesionales que hablan tu idioma.",
    "com-btn": "Solicitar Acceso al Grupo Privado",
    "cont-title": "Contacto",
    "cont-h1": "Contactar con el equipo editorial",
    "cont-desc": "¿Tienes una sugerencia para una nueva guía, encontraste un error o quieres colaborar?",
    "cont-lbl-name": "Tu Nombre",
    "cont-lbl-email": "Tu Email",
    "cont-lbl-msg": "Mensaje",
    "cont-btn": "Enviar Mensaje",
    "cont-success": "¡Gracias! Tu mensaje ha sido enviado.",
    "cont-error": "Hubo un error al enviar el formulario. Por favor, inténtalo de nuevo."
  },
  en: {
    "rec-title": "Resources and Official Links",
    "rec-h1": "Official Resources",
    "rec-desc": "Verified directory of the Swiss administration and key portals for expats.",
    "rec-ch-p": "The Swiss national portal administered by the federal government in 5 languages.",
    "rec-ch-link": "Visit ch.ch &rarr;",
    "rec-sem-p": "State Secretariat for Migration. Federal directives on permits and naturalization.",
    "rec-sem-link": "Visit SEM &rarr;",
    "rec-comp-p": "Platform to compare health insurance premiums canton by canton, as well as car insurance.",
    "rec-comp-link": "Visit Comparis &rarr;",
    "rec-canton-title": "Your Canton's Website",
    "rec-canton-p": "Your canton manages tax collection, unemployment, and permit issuance. E.g. vd.ch (Vaud), zh.ch (Zurich).",
    "com-nav": "Community",
    "com-h1": "From a help group to a knowledge platform.",
    "com-desc": "Our website extracts true knowledge and the most recurring problems that arise daily from our vibrant Facebook community.",
    "com-p1": "<strong>Españoles en Suiza que realmente se ayudan</strong> was born as a private FB group to filter noise and provide reliable answers to newcomers.",
    "com-p2": "Today we are thousands of members adding value, warning about rental scams and helping to understand Swiss bureaucracy.",
    "com-li1": "Fast resolution of doubts about permits and LAMal.",
    "com-li2": "Direct transfer accommodation offers (no agency).",
    "com-li3": "Networking and recommendation of professionals speaking your language.",
    "com-btn": "Request Access to the Private Group",
    "cont-title": "Contact",
    "cont-h1": "Contact the editorial team",
    "cont-desc": "Do you have a suggestion for a new guide, found a bug or want to collaborate?",
    "cont-lbl-name": "Your Name",
    "cont-lbl-email": "Your Email",
    "cont-lbl-msg": "Message",
    "cont-btn": "Send Message",
    "cont-success": "Thank you! Your message has been sent.",
    "cont-error": "There was an error sending the form. Please try again."
  },
  fr: {
    "rec-title": "Ressources et Liens Officiels",
    "rec-h1": "Ressources Officielles",
    "rec-desc": "Annuaire vérifié de l'administration suisse et portails clés pour les expatriés.",
    "rec-ch-p": "Le portail national suisse administré par le gouvernement fédéral en 5 langues.",
    "rec-ch-link": "Visiter ch.ch &rarr;",
    "rec-sem-p": "Secrétariat d'État aux migrations. Directives fédérales sur les permis et naturalisation.",
    "rec-sem-link": "Visiter le SEM &rarr;",
    "rec-comp-p": "Plateforme pour comparer les primes d'assurance maladie canton par canton.",
    "rec-comp-link": "Visiter Comparis &rarr;",
    "rec-canton-title": "Le site de votre Canton",
    "rec-canton-p": "Votre canton gère la perception des impôts, le chômage et la délivrance des permis. Par exemple vd.ch (Vaud), ge.ch (Genève).",
    "com-nav": "Communauté",
    "com-h1": "D'un groupe d'entraide à cette plateforme de connaissances.",
    "com-desc": "Notre site web extrait de notre vibrante communauté Facebook les vraies connaissances et les problèmes récurrents.",
    "com-p1": "<strong>Españoles en Suiza que realmente se ayudan</strong> est né comme groupe privé pour filtrer le bruit et fournir des réponses fiables.",
    "com-p2": "Aujourd'hui, nous sommes des milliers de membres apportant de la valeur et prévenant les arnaques de location.",
    "com-li1": "Résolution rapide des doutes sur les permis et la LAMal.",
    "com-li2": "Offres de logement en transfert direct (sans agence).",
    "com-li3": "Réseautage et recommandation de professionnels.",
    "com-btn": "Demander l'accès au groupe privé",
    "cont-title": "Contact",
    "cont-h1": "Contacter l'équipe éditoriale",
    "cont-desc": "Avez-vous une suggestion pour un guide, avez-vous trouvé une erreur ou souhaitez-vous collaborer ?",
    "cont-lbl-name": "Votre Nom",
    "cont-lbl-email": "Votre E-mail",
    "cont-lbl-msg": "Message",
    "cont-btn": "Envoyer le Message",
    "cont-success": "Merci ! Votre message a été envoyé.",
    "cont-error": "Une erreur s'est produite. Veuillez réessayer."
  },
  de: {
    "rec-title": "Ressourcen und Offizielle Links",
    "rec-h1": "Offizielle Ressourcen",
    "rec-desc": "Verifiziertes Verzeichnis der Schweizer Verwaltung und der wichtigsten Portale für Auswanderer.",
    "rec-ch-p": "Das in 5 Sprachen verfügbare nationale Schweizer Portal, das vom Bund verwaltet wird.",
    "rec-ch-link": "Besuchen ch.ch &rarr;",
    "rec-sem-p": "Staatssekretariat für Migration. Richtlinien des Bundes zu Bewilligungen und Einbürgerung.",
    "rec-sem-link": "Besuchen SEM &rarr;",
    "rec-comp-p": "Plattform zum Vergleich der Krankenkassenprämien Kanton für Kanton.",
    "rec-comp-link": "Besuchen Comparis &rarr;",
    "rec-canton-title": "Die Website Ihres Kantons",
    "rec-canton-p": "Ihr Kanton verwaltet Steuern, Arbeitslosigkeit und die Ausstellung von Ausweisen. Z.B. zh.ch (Zürich).",
    "com-nav": "Gemeinschaft",
    "com-h1": "Von einer Hilfsgruppe zu dieser Wissensplattform.",
    "com-desc": "Unsere Website extrahiert das wahre Wissen und die häufigsten Probleme, die täglich in unserer Facebook-Community auftreten.",
    "com-p1": "<strong>Españoles en Suiza que realmente se ayudan</strong> wurde als private Gruppe gegründet, um zuverlässige Antworten zu geben.",
    "com-p2": "Heute sind wir Tausende von Mitgliedern, die vor Mietbetrug warnen und helfen, die Schweizer Bürokratie zu verstehen.",
    "com-li1": "Schnelle Klärung von Fragen zu Bewilligungen und KVG.",
    "com-li2": "Unterkunftsangebote zur direkten Übernahme (ohne Agentur).",
    "com-li3": "Networking und Empfehlung von Fachleuten.",
    "com-btn": "Zugang zur privaten Gruppe anfordern",
    "cont-title": "Kontakt",
    "cont-h1": "Kontaktieren Sie die Redaktion",
    "cont-desc": "Haben Sie einen Vorschlag für einen Leitfaden, einen Fehler gefunden oder möchten Sie mitarbeiten?",
    "cont-lbl-name": "Ihr Name",
    "cont-lbl-email": "Ihre E-Mail",
    "cont-lbl-msg": "Botschaft",
    "cont-btn": "Nachricht Senden",
    "cont-success": "Vielen Dank! Ihre Nachricht wurde gesendet.",
    "cont-error": "Beim Senden ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut."
  },
  it: {
    "rec-title": "Risorse e Link Ufficiali",
    "rec-h1": "Risorse Ufficiali",
    "rec-desc": "Elenco verificato dell'amministrazione svizzera e dei portali principali per gli espatriati.",
    "rec-ch-p": "Il portale nazionale svizzero amministrato in 5 lingue.",
    "rec-ch-link": "Visita ch.ch &rarr;",
    "rec-sem-p": "Segreteria di Stato della migrazione. Direttive federali sui permessi e la naturalizzazione.",
    "rec-sem-link": "Visita SEM &rarr;",
    "rec-comp-p": "Piattaforma per confrontare i premi dell'assicurazione malattie cantone per cantone.",
    "rec-comp-link": "Visita Comparis &rarr;",
    "rec-canton-title": "Il sito del tuo Cantone",
    "rec-canton-p": "Il tuo cantone gestisce la riscossione delle tasse, la disoccupazione e il rilascio dei permessi. Es. ti.ch (Ticino).",
    "com-nav": "Comunità",
    "com-h1": "Da un gruppo di aiuto a questa piattaforma di conoscenza.",
    "com-desc": "Il nostro sito oestrae la vera conoscenza e i problemi più ricorrenti dalla nostra comunità di Facebook.",
    "com-p1": "<strong>Españoles en Suiza que realmente se ayudan</strong> è nato come gruppo privato per fornire risposte affidabili.",
    "com-p2": "Oggi siamo migliaia di membri che mettono in guardia contro le truffe sugli affitti.",
    "com-li1": "Risoluzione rapida di dubbi sui permessi e LAMal.",
    "com-li2": "Offerte di alloggi in trasferimento diretto (senza agenzia).",
    "com-li3": "Rete e raccomandazione di professionisti.",
    "com-btn": "Richiedi l'accesso al gruppo",
    "cont-title": "Contatto",
    "cont-h1": "Contatta il team editoriale",
    "cont-desc": "Hai un suggerimento o vuoi collaborare?",
    "cont-lbl-name": "Il tuo Nome",
    "cont-lbl-email": "La tua E-mail",
    "cont-lbl-msg": "Messaggio",
    "cont-btn": "Inviare un messaggio",
    "cont-success": "Grazie! Il tuo messaggio è stato inviato.",
    "cont-error": "Si è verificato un errore. Per favore, riprova."
  }
};

let appStr = fs.readFileSync('app.js', 'utf8');

for (const lang in d) {
  let entries = Object.keys(d[lang]).map(k => `"${k}": "${d[lang][k]}"`).join(',\n            ');
  // insert before `}, \n \t ${nextLang}: { ` or end of object
  let blockRegex = new RegExp(`(${lang}: \\{\\s*[\\s\\S]*?)(\\n\\s*\\},)`, 'g');
  appStr = appStr.replace(blockRegex, `$1,\n            ${entries}$2`);
}

fs.writeFileSync('app.js', appStr, 'utf8');
console.log('App.js translations appended successfully.');
